import { useEffect, useState } from 'react'
import { Navigate, Link } from 'react-router-dom'
import { ArrowUpRight, Plus, Layers3, Package, Trash2, UploadCloud, X, CheckCircle2 } from 'lucide-react'
import { api, getErrorMessage, getImageUrl } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import { Loading } from '../components/Loading'

const emptyForm = { title: '', description: '', category: '', tags: '', featured: false, previewImage: null, downloadFile: null }
export default function Admin() {
  const { user, checking } = useAuth(); const [categories, setCategories] = useState([]); const [items, setItems] = useState([]); const [form, setForm] = useState(emptyForm); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [activeTab, setActiveTab] = useState('mockups'); const [categoryName, setCategoryName] = useState(''); const [categoryDescription, setCategoryDescription] = useState('')
  const refresh = async () => { const [c, m] = await Promise.all([api.get('/categories'), api.get('/mockups?limit=50')]); setCategories(c.data); setItems(m.data.data || []) }
  useEffect(() => { if (user?.role === 'admin') refresh().catch(e => setError(getErrorMessage(e))).finally(() => setLoading(false)); else setLoading(false) }, [user])
  if (checking) return <div className="container admin-loading"><Loading label="Checking account…"/></div>
  if (!user) return <Navigate to="/login" replace />
  if (user.role !== 'admin') return <section className="admin-page"><div className="container"><div className="notice notice-error">This area is only available to admin accounts.</div><Link to="/browse" className="btn btn-dark">Return to library</Link></div></section>
  const submitMockup = async e => { e.preventDefault(); setError(''); setSuccess(''); setSaving(true); try { if (!form.previewImage || !form.downloadFile) throw new Error('Choose both a preview image and a downloadable file.'); const body = new FormData(); body.append('title', form.title); body.append('description', form.description); body.append('category', form.category); body.append('tags', form.tags); body.append('featured', String(form.featured)); body.append('previewImage', form.previewImage); body.append('downloadFile', form.downloadFile); await api.post('/mockups', body, { headers: { 'Content-Type': 'multipart/form-data' } }); setSuccess('Mockup uploaded successfully.'); setForm(emptyForm); await refresh() } catch (e) { setError(getErrorMessage(e)) } finally { setSaving(false) } }
  const createCategory = async e => { e.preventDefault(); setError(''); setSuccess(''); try { await api.post('/categories', { name: categoryName, description: categoryDescription }); setCategoryName(''); setCategoryDescription(''); setSuccess('Category created successfully.'); await refresh() } catch (e) { setError(getErrorMessage(e)) } }
  const deleteMockup = async id => { if (!window.confirm('Delete this mockup and its uploaded files? This cannot be undone.')) return; try { await api.delete(`/mockups/${id}`); setItems(old => old.filter(x => x._id !== id)); setSuccess('Mockup deleted.'); } catch (e) { setError(getErrorMessage(e)) } }
  const deleteCategory = async id => { if (!window.confirm('Delete this category? Categories containing mockups cannot be deleted.')) return; try { await api.delete(`/categories/${id}`); await refresh(); setSuccess('Category deleted.') } catch (e) { setError(getErrorMessage(e)) } }
  return <section className="admin-page"><div className="container"><div className="admin-heading"><div><p className="eyebrow"><span className="eyebrow-line"/> YOUR CONTROL ROOM</p><h1>Studio <span className="serif-italic">dashboard.</span></h1><p>Welcome back, {user.name}. Keep the library looking good.</p></div><Link to="/browse" className="text-link">View public library <ArrowUpRight size={16}/></Link></div>{error && <div className="notice notice-error"><X size={16}/>{error}</div>}{success && <div className="notice notice-success"><CheckCircle2 size={16}/>{success}</div>}
    <div className="admin-stats"><div><span className="stat-icon"><Layers3 size={18}/></span><p>Published mockups</p><strong>{items.length}</strong></div><div><span className="stat-icon"><Package size={18}/></span><p>Categories</p><strong>{categories.length}</strong></div><div><span className="stat-icon"><UploadCloud size={18}/></span><p>Total downloads</p><strong>{items.reduce((sum, item) => sum + (item.downloads || 0), 0).toLocaleString()}</strong></div></div>
    <div className="admin-tabs"><button className={activeTab === 'mockups' ? 'active' : ''} onClick={() => setActiveTab('mockups')}>Mockups <span>{items.length}</span></button><button className={activeTab === 'upload' ? 'active' : ''} onClick={() => setActiveTab('upload')}><Plus size={15}/> Add mockup</button><button className={activeTab === 'categories' ? 'active' : ''} onClick={() => setActiveTab('categories')}>Categories <span>{categories.length}</span></button></div>
    {loading ? <Loading label="Loading studio…"/> : <>
      {activeTab === 'upload' && <form className="admin-panel upload-form" onSubmit={submitMockup}><div className="panel-heading"><div><p className="eyebrow">NEW RESOURCE</p><h2>Add a mockup</h2></div><span className="required-note">* Required fields</span></div><div className="form-grid"><label>Mockup title *<input required maxLength={150} value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="e.g. Minimal business card mockup"/></label><label>Category *<select required value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}><option value="">Choose a category</option>{categories.map(c => <option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label className="full-field">Description<textarea maxLength={2000} rows="4" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Tell creatives what makes this mockup useful…"/></label><label className="full-field">Tags <input value={form.tags} onChange={e => setForm({ ...form, tags: e.target.value })} placeholder="branding, stationery, minimal (comma separated)"/></label><label className="file-drop"><UploadCloud size={23}/><strong>Preview image *</strong><span>{form.previewImage?.name || 'JPG, PNG or WebP — select image'}</span><input type="file" accept="image/jpeg,image/png,image/webp" required onChange={e => setForm({ ...form, previewImage: e.target.files?.[0] || null })}/></label><label className="file-drop"><Package size={23}/><strong>Download file *</strong><span>{form.downloadFile?.name || 'PSD, ZIP, AI, EPS, INDD or PDF'}</span><input type="file" accept=".psd,.zip,.ai,.eps,.indd,.pdf,.sketch,.fig,.xd,.jpg,.png" required onChange={e => setForm({ ...form, downloadFile: e.target.files?.[0] || null })}/></label><label className="checkbox-label"><input type="checkbox" checked={form.featured} onChange={e => setForm({ ...form, featured: e.target.checked })}/> Feature this mockup on the homepage</label></div><div className="form-actions"><button className="btn btn-dark" disabled={saving}>{saving ? 'Uploading…' : 'Publish mockup'} <ArrowUpRight size={16}/></button><p>Large files may take a little while to upload.</p></div></form>}
      {activeTab === 'mockups' && <div className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">LIBRARY CONTENT</p><h2>All mockups</h2></div><button className="btn btn-dark" onClick={() => setActiveTab('upload')}><Plus size={16}/> Add mockup</button></div>{items.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Mockup</th><th>Category</th><th>Downloads</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(item => <tr key={item._id}><td><div className="table-mockup"><img src={getImageUrl(item.previewImage)} alt=""/><span>{item.title}</span></div></td><td>{item.category?.name || '—'}</td><td>{item.downloads || 0}</td><td><span className="status-live">● Published</span></td><td><button className="delete-btn" onClick={() => deleteMockup(item._id)} title="Delete mockup"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div> : <div className="empty-state"><div className="empty-icon">✳</div><h3>No mockups yet</h3><p>Upload your first mockup to populate the public library.</p><button className="btn btn-dark" onClick={() => setActiveTab('upload')}>Add first mockup <Plus size={15}/></button></div>}</div>}
      {activeTab === 'categories' && <div className="category-admin-grid"><form className="admin-panel category-create-form" onSubmit={createCategory}><p className="eyebrow">ORGANIZE THE LIBRARY</p><h2>Create a category</h2><label>Category name *<input required value={categoryName} onChange={e => setCategoryName(e.target.value)} placeholder="e.g. Packaging"/></label><label>Description<textarea rows="3" value={categoryDescription} onChange={e => setCategoryDescription(e.target.value)} placeholder="A short category description"/></label><button className="btn btn-dark">Create category <Plus size={15}/></button></form><div className="admin-panel category-list-panel"><p className="eyebrow">EXISTING CATEGORIES</p><h2>Your categories</h2>{categories.map((c, i) => <div className="category-admin-row" key={c._id}><span className="category-row-number">0{i + 1}</span><div><strong>{c.name}</strong><small>{c.description || 'No description'}</small></div><button className="delete-btn" title={`Delete ${c.name}`} onClick={() => deleteCategory(c._id)}><Trash2 size={15}/></button></div>)}</div></div>}
    </>}</div></section>
}
