import { useState } from 'react'
import { Link, useNavigate, useLocation } from 'react-router-dom'
import { ArrowLeft, ArrowUpRight, Eye, EyeOff, Sparkles } from 'lucide-react'
import { api, getErrorMessage } from '../lib/api'
import { useAuth } from '../context/AuthContext'

export default function Auth({ mode = 'login' }) {
  const isRegister = mode === 'register'; const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const submit = async e => { e.preventDefault(); setError(''); setLoading(true); try { const { data } = await api.post(`/auth/${isRegister ? 'register' : 'login'}`, isRegister ? { name, email, password } : { email, password }); login(data); navigate(data.user.role === 'admin' ? '/admin' : (location.state?.from || '/browse')) } catch (err) { setError(getErrorMessage(err)) } finally { setLoading(false) } }
  return <section className="auth-page"><div className="auth-aside"><Link to="/" className="brand auth-brand"><span className="brand-mark">J</span><span>JABA<span className="brand-light"> MOCKUPS</span></span></Link><div className="auth-aside-content"><div className="auth-spark"><Sparkles size={22}/></div><p className="eyebrow">A HOME FOR GOOD IDEAS</p><h2>Make your work<br/>look like <em>your work.</em></h2><p>Find your canvas, bring your vision to life, and make your next project impossible to ignore.</p><div className="auth-aside-footer"><span>01 / DISCOVER</span><span>02 / CREATE</span><span>03 / SHARE</span></div></div><div className="auth-aside-decoration">J.</div></div><div className="auth-main"><Link to="/" className="back-link auth-back"><ArrowLeft size={15}/> Back to home</Link><div className="auth-form-wrap"><p className="eyebrow"><span className="eyebrow-line"/> {isRegister ? 'START SOMETHING GOOD' : 'WELCOME BACK'}</p><h1>{isRegister ? 'Join the creative side.' : 'Good to see you again.'}</h1><p className="auth-subtitle">{isRegister ? 'Create an account to start exploring the library.' : 'Log in to pick up where your creativity left off.'}</p><form onSubmit={submit} className="auth-form">{isRegister && <label>Your name<input autoComplete="name" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Abdi Milki" required/></label>}<label>Email address<input type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" required/></label><label>Password<div className="password-input"><input type={showPassword ? 'text' : 'password'} autoComplete={isRegister ? 'new-password' : 'current-password'} value={password} onChange={e => setPassword(e.target.value)} placeholder={isRegister ? 'At least 6 characters' : 'Enter your password'} minLength={isRegister ? 6 : undefined} required/><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label="Toggle password visibility">{showPassword ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div></label>{error && <div className="notice notice-error">{error}</div>}<button className="btn btn-dark auth-submit" type="submit" disabled={loading}>{loading ? 'Please wait…' : isRegister ? 'Create account' : 'Log in'} <ArrowUpRight size={17}/></button></form><p className="auth-switch">{isRegister ? 'Already have an account?' : 'New around here?'} <Link to={isRegister ? '/login' : '/register'}>{isRegister ? 'Log in' : 'Create an account'}</Link></p><p className="auth-terms">By continuing, you agree to use JABA MOCKUPS responsibly and respect creators' work.</p></div></div></section>
}
