import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowRight, ArrowUpRight, Search, Sparkles, Shapes, Package, Shirt, Smartphone, Layers3, Palette } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { api, getErrorMessage } from '../lib/api'
import MockupCard from '../components/MockupCard'
import { Loading } from '../components/Loading'

const categoryIcons = [Shapes, Package, Shirt, Smartphone, Layers3, Palette]
const categoryColors = ['#e6e9db', '#f2dfce', '#dbe5f0', '#e7ddf3', '#e3e8c9', '#f4d9db']
export default function Home() {
  const [categories, setCategories] = useState([])
  const [mockups, setMockups] = useState([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [error, setError] = useState('')
  const navigate = useNavigate()
  useEffect(() => {
    Promise.all([api.get('/categories'), api.get('/mockups?limit=8')]).then(([c, m]) => { setCategories(c.data); setMockups(m.data.data || []) }).catch(e => setError(getErrorMessage(e))).finally(() => setLoading(false))
  }, [])
  const submitSearch = (e) => { e.preventDefault(); navigate(`/browse${search.trim() ? `?q=${encodeURIComponent(search.trim())}` : ''}`) }
  return <>
    <section className="hero-section"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="container hero-grid"><div className="hero-copy"><div className="hero-kicker"><span className="kicker-star">✳</span> THE MOCKUP LIBRARY FOR CREATIVES</div><h1>Make your ideas<br/>feel <span className="headline-accent">real.</span></h1><p className="hero-description">Beautiful mockups that help your best work make its first impression. Find the right canvas, add your creativity, and bring it to life.</p><form className="hero-search" onSubmit={submitSearch}><Search size={19}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search mockups, brands, packaging…" aria-label="Search mockups"/><button type="submit">Search <ArrowUpRight size={16}/></button></form><div className="hero-proof"><div className="avatar-stack"><span>A</span><span>M</span><span>J</span><span>+</span></div><p><strong>For independent creatives</strong><br/>Design something worth sharing.</p></div></div>
      <div className="hero-art"><div className="hero-art-label label-top"><span className="label-dot"/> CREATIVE TOOLKIT <span>NO. 001</span></div><div className="hero-poster poster-back"><span>MAKE<br/>IT<br/><i>MATTER.</i></span><small>YOUR NEXT BIG IDEA STARTS HERE</small></div><div className="hero-poster poster-front"><div className="poster-shape shape-circle"/><div className="poster-shape shape-arch"/><div className="poster-caption"><span>STUDIO</span><strong>form / function</strong><small>OBJECTS FOR EVERYDAY LIVING</small></div><div className="poster-stamp">J<br/><span>®</span></div></div><div className="floating-note"><Sparkles size={15}/><span>Good ideas<br/><strong>look good here.</strong></span></div><div className="hero-art-label label-bottom"><span>FIG. 01</span> DESIGN THAT SPEAKS <ArrowDownRight size={15}/></div></div>
    </div><div className="container hero-bottom-line"><span>YOUR NEXT PROJECT, BETTER PRESENTED.</span><span>SCROLL TO EXPLORE <ArrowDownRight size={14}/></span></div></section>
    <section className="section categories-section"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span className="eyebrow-line"/> FIND YOUR STARTING POINT</p><h2>Good work starts<br/>with the <span className="serif-italic">right canvas.</span></h2></div><Link to="/browse" className="text-link">View all mockups <ArrowUpRight size={17}/></Link></div><div className="category-grid">{categories.slice(0, 6).map((category, index) => { const Icon = categoryIcons[index % categoryIcons.length]; return <Link to={`/browse?category=${encodeURIComponent(category.slug || category._id)}`} className="category-card" key={category._id} style={{ '--category-bg': categoryColors[index % categoryColors.length] }}><div className="category-visual"><Icon size={42} strokeWidth={1.2}/><span className="category-number">0{index + 1}</span></div><div className="category-info"><div><h3>{category.name}</h3><p>{category.description || 'Explore the collection'}</p></div><span className="round-arrow"><ArrowUpRight size={17}/></span></div></Link> })}</div>{!categories.length && !loading && <p className="inline-note">Your categories will appear here once your backend has categories.</p>}</div></section>
    <section className="section featured-section"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span className="eyebrow-line"/> A FEW GOOD THINGS</p><h2>Fresh from the <span className="serif-italic">library.</span></h2></div><Link to="/browse" className="text-link">Explore all <ArrowUpRight size={17}/></Link></div>{error && <div className="notice notice-error">{error}. Make sure your backend is running at localhost:5000.</div>}{loading ? <Loading/> : mockups.length ? <div className="mockup-grid">{mockups.slice(0, 8).map((mockup, index) => <MockupCard key={mockup._id} mockup={mockup} index={index}/>)}</div> : <div className="empty-library"><div className="empty-library-icon"><Layers3 size={28}/></div><div><h3>Your creative library starts here.</h3><p>Once you add mockups through your backend, they will show up in this collection.</p></div><Link className="btn btn-outline" to="/browse">Browse library <ArrowRight size={16}/></Link></div>}</div></section>
    <section className="cta-section"><div className="container cta-inner"><div className="cta-symbol">J<span>✳</span></div><div><p className="eyebrow">YOUR IDEAS DESERVE THIS</p><h2>Ready to make<br/>something <em>real?</em></h2></div><div className="cta-right"><p>Find a mockup that feels right. Then make it yours.</p><Link to="/browse" className="btn btn-lime">Find your mockup <ArrowUpRight size={17}/></Link></div></div></section>
  </>
}
